add_newline = false

format = """
$os$username$hostname$directory$git_branch$git_status$package$nodejs$python$rust$docker_context$aws$gcloud$kubernetes$terraform\
$jobs$cmd_duration
$battery$time$custom$character
"""

[os]
disabled = false
style = "#575653"
format = "[$symbol]($style) "

[os.symbols]
Macos = ""

[directory]
style = "bold #575653"
truncation_length = 3
read_only = " 󰌾"

[directory.substitutions]
"~" = "󰋜 ~"
"Documents" = "󰈙 Documents"
"Downloads" = "󰉍 Downloads"
"Desktop" = "󰧨 Desktop"
"Projects" = " Projects"
"Developer" = " Developer"
"Code" = " Code"
".dotfiles" = " .dotfiles"

[character]
success_symbol = "[❯](#4385BE)"
error_symbol = "[❯](#AF3029)"

[username]
show_always = false
style_user = "#575653"
style_root = "bold #AF3029"
format = "[$user]($style) "

[hostname]
ssh_only = true
style = "#BC5215"
format = "@ [$hostname]($style) "

[git_branch]
symbol = " "
style = "#4385BE"

[git_status]
style = "#AF3029"
ahead = "↑"
behind = "↓"
diverged = "⇡⇣"
modified = "~"
untracked = "?"
staged = "+"
deleted = "✗"

[package]
symbol = "󰏗 "
style = "#BC5215"
format = "[$symbol$version]($style) "

[nodejs]
symbol = " "
style = "#66800B"
detect_files = ["package.json"]

[python]
symbol = " "
style = "#BC5215"
detect_files = ["requirements.txt", "pyproject.toml"]

[rust]
symbol = " "
style = "#AF3029"

[docker_context]
symbol = " "
style = "#4385BE"
only_with_files = true

[aws]
symbol = " "
style = "#BC5215"
format = "[$symbol($profile)(\\($region\\))]($style) "

[gcloud]
symbol = "󱇶 "
style = "#4385BE"
format = "[$symbol($project)]($style) "

[kubernetes]
disabled = false
symbol = "󱃾 "
style = "#66800B"
format = "[$symbol$context(\\($namespace\\))]($style) "

[terraform]
symbol = "󱁢 "
style = "#4385BE"
format = "[$symbol$workspace]($style) "

[jobs]
symbol = "󰜎 "
style = "#BC5215"
format = "[$symbol$number]($style) "
threshold = 1

[cmd_duration]
min_time = 2_000
style = "#575653"
format = " took [$duration]($style)"

[battery]
disabled = false
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 30
style = "#AF3029"
discharging_symbol = "󰁺 "

[[battery.display]]
threshold = 60
style = "#BC5215"
discharging_symbol = "󰁾 "

[[battery.display]]
threshold = 100
style = "#66800B"
discharging_symbol = "󰁹 "

[time]
disabled = false
style = "#575653"
format = "[$time]($style) "
time_format = "%H:%M"

[custom.timeofday]
command = """
hour=$(date +%H)
if [ $hour -ge 5 ] && [ $hour -lt 12 ]; then echo "☀️"
elif [ $hour -ge 12 ] && [ $hour -lt 17 ]; then echo "🌤"
elif [ $hour -ge 17 ] && [ $hour -lt 21 ]; then echo "🌅"
else echo "🌙"
fi
"""
when = true
shell = ["bash", "--noprofile", "--norc"]
format = "[$output]($style) "
style = "#575653"
